OPENAI_API_KEY = "sk-rtJTuV9Dm03wfP-yltz9kz31rEW_ltsapsePUEpE1gT3BlbkFJF2oK2n1YYBj44K71uyaLsbc66v1bBxeKiwqYHNqAAA"
GOOGLE_API_KEY = "AIzaSyBNZwaI8yS3VV2_xOye6T3SyTM51Y0n3oA"
ANTHROPIC_API_KEY = "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"